config/routes.rb
Rails.application.routes.draw do
      devise_for :users
      get 'books/search', to: 'books#search', as: :search
  root to: 'pages#home'
  resources :books do
    resources :transactions
  end
get 'pages/dashboard', to: 'pages#dashboard', as: :dashboard
get 'pages/dashboard/update/:status/:id', to: 'pages#update', as: :update_dashboard

resources :users, only: ['edit', 'update']
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  enum category: ['policier', 'roman francais', 'roman etranger', 'livre de voyage', 'S.F.', 'heroic Fantasy']

  mount_uploader :photo, PhotoUploader
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :transactions


  mount_uploader :avatar, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || dashboard_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def dashboard
    @books = Book.where(user: current_user)

  end

  def search

    @users = User.geocoded
    @markers = @users.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: user })
      }
    end

  end

  def index
    @s = params[:search]

    if @s.nil?
      @books = []
      b = Book.all
      @books = b.reject {|item| item.user == current_user}

    else
      @books = []
      b = Book.where("name ilike ?", "%#{@s}%")
      @books = b.reject {|item| item.user == current_user}

    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(books_params)
    @book.user = current_user
    if @book.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(books_params)
    redirect_to dashboard_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to dashboard_path
  end

  private

  def books_params
    params.require(:book).permit(:name, :author, :picture_id, :category, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard

      @books = current_user.books

      @transactions = current_user.transactions
      @transactionsOwner = Transaction.where(book_id: current_user.books.ids)


  end

  def update
    @t = Transaction.find(params[:id])
    @t.status = params[:status]
    @t.update(transaction_params)
    redirect_to dashboard_path("transations")
  end

  private

  def transaction_params
    params.permit(:status)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def dashboard

  end

  def index
    @book = Book.find(params[:book_id])
    @transactions = Transaction.find(params[:user_id])
  end

  def new
    @book = Book.find(params[:book_id])
    @transaction = Transaction.new
    @transaction.book = @book
    @begin = Date.today
    @end = Date.tomorrow

  end

  def create

    @transaction = Transaction.new()
    @transaction.user = current_user
    @transaction.book = Book.find(params[:book_id])
    db = date_to_array(params[:begin])
    de = date_to_array(params[:end])
    @transaction.date_begin = Date.new(db[0],db[1],db[2])
    @transaction.end_date = Date.new(de[0],de[1],de[2])
    @transaction.status = 'av'
    @transaction.save

    redirect_to dashboard_path
  end

  def update
    @transaction.update(transaction_params)
  end

  def destroy
    @transaction.destroy

    redirect_to transactions_path
  end

  private

  def date_to_array(d)
    a = []
    dd = d.split('-')
    dd.each { |item| a << item.to_i}
    a

  end

  def transaction_params
    params.require(:transaction).permit(:date_begin, :end_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])

  end

  def update
     @user = User.find(params[:id])
     @user.update(user_strong)
     redirect_to dashboard_path(status: 'livres')
  end

  private

  def user_strong
    params.require(:user).permit(:first_name, :last_name, :avatar, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(book) do |f| %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
<% end %>

app/views/books/_info_window.html.erb
<% if user == current_user %>

<h3>It's me </h3>
<% else %>
<h6><%= user.first_name %>'s Books</h6>
<div class="cards" style="display: flex; flex-wrap: wrap">
  <% user.books.each do |book| %>
  <div class="card" style="margin: 5px; width: 100%">
    <%= link_to book.name, new_book_transaction_path(book)  %>
  </div>

  <% end %>
</div>
<% end %>

app/views/books/edit.html.erb
  <h1>BOOK N° <%= @book.id %></h1>

  <div class="container">
    <%= simple_form_for(@book) do |f| %>
    <div class="form-row d-flex">
      <div class="form-group col-6">
        <%= f.input :name %>
      </div>
      <div class="form-group col-6">
        <%= f.input :author %>
      </div>
    </div>
    <%= f.input :price_per_day %>
    <%= f.input :category, collection: Book.categories.keys %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit class:"btn btn-primary"%>
    <% end %>
    <hr>
    <%= link_to 'Return to dashboard', dashboard_path(status: 'livres'), class: 'btn btn-sm btn-info'   %>
  </div>

app/views/books/index.html.erb
<div class="container" style="margin-bottom: 32px">
  <h1 style="color: white">LOOKING FOR A BOOK?</h1>
  <hr>
  <div style="display: flex;justify-content: space-between">
    <%= link_to 'search on map', search_path, class: 'btn btn-sm btn-success'   %>

    <form action="books#index" method='GET'>
      <input type="text" name="search">
      <input type="submit" value="search">
    </form>
  </div>
  <hr>
  <div class="card-contain" style="display: flex;flex-wrap: wrap;justify-content: center;padding-bottom: 50px">
    <% @books.each do |book| %>
    <div class="card-product">
      <%= cl_image_tag book.photo, height: 300, width: 400, crop: :fit %>
      <div class="card-product-infos">
        <h2><%= book.name %></h2>
        <div class="info">
          <div><%= book.price_per_day %> €</div>
          <div><%= book.author %></div>
          <div><%= book.category %></div>
        </div>
        <div style="display: flex;justify-content: space-between;">
          <%= link_to 'louer', new_book_transaction_path(book), class: "btn btn-primary btn-sm"  %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <hr>
  <%= link_to 'return to dashboard', dashboard_path(status: 'livres'), class: 'btn btn-sm btn-info' %>
</div>

app/views/books/new.html.erb
<h1>CREATE A NEW BOOK</h1>
<div class="container" style="margin-bottom: 32px">
  <%= simple_form_for(@book) do |f| %>
  <div class="form-row d-flex">
    <div class="form-group col-6">
      <%= f.input :name %>
    </div>
    <div class="form-group col-6">
      <%= f.input :author %>
    </div>
  </div>
  <%= f.input :price_per_day %>
  <%= f.input :category, collection: Book.categories.keys %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit class:"btn btn-primary"%>
  <% end %>
  <hr>
  <%= link_to 'Return to dashboard', dashboard_path(status: 'livres'), class: 'btn btn-sm btn-info' %>
</div>

app/views/books/search.html.erb
<h1 style="color: white">Search by area</h1>

<div class="container pb-5">
  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-lat="<%= current_user.latitude %>"
  data-lng="<%= current_user.longitude %>"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV.fetch("MAPBOX_API_KEY") %>"
  ></div>
</div>

app/views/books/show.html.erb
<h1>Books#show for <%= @book.id %> </h1>

<%= cl_image_tag @book.photo, height: 208, width: 165, crop: :fit %>
<p><span>name : </span><%= @book.name %> </p>
<p><span>price : </span><%= @book.price_per_day %> €</p>
<p><span>author : </span><%= @book.author %> </p>
<p><span>category : </span><%= @book.category %> </p>

app/views/layouts/application.html.erb
<style>
    body {background: -webkit-radial-gradient(center, ellipse cover, #ffaf4b 0%,#ff920a 100%);
  }
</style>


<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%= render 'shared/navbar' %>
  <div class="alertClass">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

  <div class="page">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/dashboard.html.erb
<style>
  .nav-item.active{
    background-color: rgba(255,255,255,0.5);
    color: white;
  }
</style>

<div id="dashboard" style="padding: 30px 0">
  <div class="container">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500); margin-bottom: 16px">
      Bibliothèque
    </div>

    <div class="row">
      <div class="col-md-6" style="font-style: italic">
        <h2><%= link_to 'Je crée un livre', new_book_path, class: "btn btn-primary d-block"  %></h2>
      </div>
      <div class="col-md-6" style="font-style: italic">
        <h2><%= link_to "Je loue un livre", books_path, class: "btn btn-success d-block"  %></h2>
      </div>
    </div>

    <hr>





  <ul class="nav nav-pills mb-3" id="myTab" role="tablist">
    <li class="nav-item w-50">
      <a class="nav-link active text-center" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Livres</a>
    </li>
    <li class="nav-item w-50">
      <a class="nav-link text-center" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Transactions</a>
    </li>
  </ul>


  <div class="tab-content" id="myTabContent" style="background-color: rgba(255,255,255,0.5);">

    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab" style="padding: 30px 0">
      <div style="display: flex;justify-content: center;flex-wrap: wrap">
        <div class="card-contain" style="display: flex;flex-wrap: wrap;justify-content: center;padding-bottom: 50px">
          <% @books.each do |book| %>
          <div class="card-product">
            <%= cl_image_tag book.photo, height: 300, width: 400, crop: :fit %>
            <div class="card-product-infos">
              <h2><%= book.name %></h2>
              <div class="info">
                <div><%= book.price_per_day %> €</div>
                <div><%= book.author %></div>
                <div><%= book.category %></div>
              </div>
              <div style="display: flex;justify-content: space-between;">
                <div><%= link_to 'edit', edit_book_path(book)  %></div>
                <div><%= link_to 'delete', book_path(book), method: :delete  %></div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab" style="padding: 30px 0">
      <div class="container" style="border-radius: 24px;">
        <% @transactions.each do |transaction| %>
        <div class="card">
          <div class="card-footer" style="display: flex;justify-content: space-between">
            <div><%= transaction.book.name %></div>
            <div>
              <%= transaction.date_begin.to_formatted_s(:long)[0..-7] %> |
              <%= transaction.end_date.to_formatted_s(:long)[0..-7] %>
            </div>
            <div> <%= transaction.book.user.email %> </div>
            <div>
              <% if transaction.status == 'av' %>
              <button class="btn btn-danger btn-sm" disabled="">Attente de validation</button>
              <% end %>
              <% if transaction.status == 'ec' %>
              <button class="btn btn-success  btn-sm" disabled="">En cours</button>
              <% end %>
              <% if transaction.status == 'done' %>
              <button class="btn btn-primary  btn-sm" disabled="">done</button>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
        <% @transactionsOwner.each do |transaction| %>
        <div class="card" style="margin-bottom: 32px">
          <div class="card-footer" style="display: flex;justify-content: space-between">
            <div style="align-content: center; border-right: solid 1px black; padding-right: 16px"><%= transaction.book.name %></div>

            <div>
              <%= transaction.date_begin.to_formatted_s(:long)  %>
              <%= transaction.end_date.to_formatted_s(:long) %>
            </div>

            <div>
              <% if transaction.status == 'av' %>
              <%= link_to 'à valider', update_dashboard_path('ec',transaction), class: "btn btn-danger  btn-sm"  %>
              <% end %>
              <% if transaction.status == 'ec' %>
              <%= link_to 'en cours', update_dashboard_path('done',transaction), class: "btn btn-success  btn-sm"  %>
              <% end %>
              <% if transaction.status == 'done' %>
              <button class="btn btn-primary btn-sm" disabled=""> done</button>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<style>


.footer {
  display:none;
}

.navbar {
  display: none;
}

.alertClass {
  display: none;
}

.photo {
  height: 100vh;
}

</style>

<header class="photo" style="background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.4)), url(http://artsboston.org/wp-content/uploads/2016/08/Open-Book.jpg); background-size: cover">

    <div class="contain_image">
        <div class="contain__fly-in-text">
            <ul class="fly-in-text hidden">
                <li>A</li>
                <li>i</li>
                <li>r</li>
                <li>B</li>
                <li>o</li>
                <li>o</li>
                <li>k</li>
                <li>s</li>
            </ul>
        </div>
        <div class="webdev">Rent your books</div>
        <div class="gobtn">
          <% if user_signed_in? %>
          <%= link_to "let' go !", dashboard_path(status: 'livres'), class: 'btn btn-primary btn-lg rounded'   %>

          <% else %>
          <%= link_to "let' go !", new_user_session_path, class: 'btn btn-primary btn-lg rounded'   %>

          <% end %>
                      </div>
    </div>
</header>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    AirBooks. For The Readers.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
  <%= image_tag "https://carlisletheacarlisletheatre.org/images/book-logo-6.png" %>

  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

      <li class="nav-item">
        <a style="margin-right: 30px;margin-top: 10px" href="#"><%= "#{current_user.first_name} #{current_user.last_name}" %></a>
      </li>
      <li class="nav-item dropdown">
        <% if current_user.avatar.nil? %>
        <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "edit profil", edit_user_path(current_user) , class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/transactions/new.html.erb
<style>
  body {background: -webkit-radial-gradient(center, ellipse cover, #ffaf4b 0%,#ff920a 100%);
  }

  #begin, #end {
    padding: 15px;
  }
  .date-content {
    padding: 20px;
    background-color: rgba(0,0,0,0.6);
    display: flex;
    justify-content: space-between;
    color: white;
  }
  .pricePerDay {
    text-align: center;
    width: 100%;
    font-size: 1.2rem;
    color: orange;
  }

  .totalPrice {
    padding: 15px;
    text-align: center;
    background-color: white;
    border: 2px solid red;
    border-radius: 50%;
    width: 120px;
    height: 120px;
    font-size: 1.5rem;
    margin: 20px auto;
    color: red;
    line-height: 80px;

  }
  .btnRent {
    margin: 10px auto;
  }


</style>

<div id="transaction-new">
  <div class="container pt-5">

    <div class="row">
      <div class="col-4 text-center" style="border: 1px dotted lightgrey;padding: 10px;background-color: rgba(0,0,0,0.3); color: white">
        <h2 ><%= @book.name %></h2>
        <% if @book.photo ==  "livre_neutre.jpg" %>
        <%= image_tag "livre_neutre.jpg", alt: "Livre Neutre", width: 200 %>

        <% else %>
        <%= cl_image_tag @book.photo, width: 200, crop: :fit %>

        <% end %>

        <h6 style="font-style: italic;margin-top: 5px"><%= @book.author %></h6>
      </div>
      <div class="col-7 offset-1" style="border: 1px dotted lightgrey;padding: 10px;background-color: rgba(0,0,0,0.3)">
        <%= form_tag({controller: "transactions", action: "create"}, method: "post") do %>
        <div class="date">
          <div class="date-content">
            debut :
            <input type="date" id="begin" name="begin" value="<%= @begin %>">
            fin :
            <input type="date" id="end" name="end" value="<%= @end %>">
          </div>

          <br><input type="hidden" id="p" value="<%= @book.price_per_day %>"=>
        </div>
        <div class="pricePerDay">Prix : <%= @book.price_per_day %> €/jour</div>
        <div class="totalPrice"><span id="price"><%= @book.price_per_day %></span> €</div>
        <div class="btnRent">

          <button type="submit" class="btn btn-primary d-block w-100">Je loue</button>

        </div>
        <hr>
        <%= link_to 'return to dashboard', dashboard_path(status: 'livres'), class: 'btn btn-sm btn-info' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<script>
  function calcul(b, e, p) {
    e = new Date(e)
    b = new Date(b)
    return ((e - b) / 86400000) * parseFloat(p)
  }

  begin = document.getElementById('begin')
  end = document.getElementById('end')
  price = document.getElementById('price')
  p = document.getElementById('p')


  begin.addEventListener('change', (event) => {
    price.innerHTML = calcul(begin.value, end.value, p.value)
  })

  end.addEventListener('change', (event) => {
    price.innerHTML = calcul(begin.value, end.value, p.value)
  })
</script>

app/views/users/edit.html.erb
<div class="container">


  <div class="row">
    <div class="col-md-4 offset-md-4">
     <%= simple_form_for(@user) do |f| %>
     <%= f.input :first_name %>
     <%= f.input :last_name %>
     <%= f.input :address %>
     <%= f.input :avatar %>
     <%= f.input :avatar_cache, as: :hidden %>
     <%= f.submit class:"btn btn-primary"%>
     <% end %>
     <hr>
     <%= link_to 'return to dashboard', dashboard_path(status: 'livres'), class: 'btn btn-sm btn-info'   %>

   </div>


 </div>

</div>